### ISSUE TITLE
Add generic parsers & unparsers

### ISSUE THREAD

**Issue by jonsterling** [RedPRL/sml-typed-abts#10]
It would be good for this library to also have a generic parser (probably using parcom) and unparser (probably using [sml-unparse](https://github.com/jonsterling/sml-unparse)).

What would be ideal is if they were extensible, so that in an application you can parse both the "abstract notation" which is provided by this library, and additionally introduce concrete notations, as we have done in JonPRL.

In the past, the ABT parser I wrote went directly from strings to ABTs—that is, variable scope & freshness were dealt with simultaneously with parsing. Now, this is kind of nice since it lets us do everything in one pass, but to be honest, it is a little gnarly and inflexible. I'm also open to factoring the parser through a layer that doesn't have binding.

In any case, we have to deal with the parsing of operators in such a way as the intricacies of the binding of symbols do not intrude into the operator parser and induce a weird circular dependency.

One option for disentangling this dependency would be to have the user provide an operator parser like `string operator parser`; recall that in the type `'i operator`, `'i` represents the type of free symbols in the operator. That way, the operator parser doesn't need to know anything about binding of symbols! From the ABT parser, we can call `Operator.Presheaf.map phi` on such an operator, where `phi : string -> symbol` either finds the bound symbol of the correct name and uses it, or generates a new symbol in case it is free.

@jozefg Do you have any thoughts on this?

**Comment by jozefg** [comment]
I would definitely say that's a good idea. If we can delay the processing of binding than at the very least the code for handling terms in tactics will stop being so hairy. Currently you have to walk through the term and rejigger variables based on their actual strings so that they actually point to the correct binding site. If we factor through aubts (unbinding trees?) we can avoid generating real variables for things until we actually have scope information.

It'd also probably simplify the parser a bit as you noted. I'm not really deeply hooked into this library yet so take this with a grain of salt but I think that pushing as much work as you can into post processing the parsed tree is probably the right move. In that view, `string operator parser` is probably "the right thing". The more the library doesn't do automagically the less we have to hackily undo in one weird spot in JonPRL or something :)

**Comment by jonsterling** [comment]
@jozefg OK, thanks for the feedback! while waiting for some stuff to happen at work, I wrote up an AST module and a convertor from ASTs to ABTs. It was pretty straightforward, and I'll push it up soon...

As a result, we should be able to have our parser target ASTs exclusively. It will still be the responsibility of the parser to get names for metavariables right, but this is mostly trivial since metavariables cannot be bound in second-order algebraic theories. So, the parser will simply use an imperative symbol table or something locally for _metavariables_, which is perfectly sensible... But at the AST level, both variables and symbols are just strings.
