### ISSUE TITLE
Uniform interface of `ast` and `abt`.

### ISSUE THREAD

**Issue by favonia** [RedPRL/sml-typed-abts#96]
Could `abt` and `ast` be made more uniform so that one can easily write a function that works on both? For example, is it possible to reuse `views` in `ast`?

**Comment by jonsterling** [comment]
@favonia I've been wondering the same thing for about a year... I think the reason I wasn't able to unify them was an issue of sort-checking, but I can't remember exactly. I think part of the problem is that this well-sorted-from-the-start approach that the abt library enforces is not necessarily a very good design.

If you can think of a way to make this work, then I would be delighted to incorporate it.
